name: Run Backend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode prompts file
        if: ${{ secrets.PROMPT_BASE64 != '' }}
        run: |
          echo "${{ secrets.PROMPT_BASE64 }}" | base64 -d > backend/data/prompts/prompts.py

      - name: Decode archetype file
        if: ${{ secrets.ARCHETYPE_BASE64 != '' }}
        run: |
          echo "${{ secrets.ARCHETYPE_BASE64 }}" | base64 -d > backend/data/archetype.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest backend/tests
